'use client';
import { Arrow } from '@/components/arrow';
import { useState } from 'react';
import type { ContactFormValues } from '@/lib/content';
import { validateContact } from '@/lib/contact';
export function ContactForm() {
 const [values, setValues] = useState<ContactFormValues>({ name: '', email: '', phone: '', message: '' }); const [errors, setErrors] = useState<Partial<Record<keyof ContactFormValues, string>>>({}); const [success, setSuccess] = useState(false);
 return <form className="contact-form" noValidate onSubmit={e => { e.preventDefault(); const next = validateContact(values); setErrors(next); setSuccess(false); const first = (Object.keys(next) as (keyof ContactFormValues)[])[0]; if (first) document.getElementById(first)?.focus(); else setSuccess(true); }}><div className="form-grid">{(['name','email','phone','message'] as const).map(field => <div className={field === 'message' ? 'field full' : 'field'} key={field}><label htmlFor={field}>{field === 'phone' ? 'Phone (digits only)' : field.charAt(0).toUpperCase() + field.slice(1)} <span className="muted">/ required</span></label>{field === 'message' ? <textarea id={field} required maxLength={5000} rows={5} value={values[field]} onChange={e => { setValues({ ...values, [field]: e.target.value }); setSuccess(false); }} aria-invalid={!!errors[field]} aria-describedby={errors[field] ? `${field}-error` : undefined} /> : <input id={field} required type={field === 'email' ? 'email' : field === 'phone' ? 'tel' : 'text'} autoComplete={field === 'phone' ? 'tel' : field} inputMode={field === 'phone' ? 'numeric' : undefined} maxLength={field === 'name' ? 100 : 254} value={values[field]} onChange={e => { setValues({ ...values, [field]: e.target.value }); setSuccess(false); }} aria-invalid={!!errors[field]} aria-describedby={errors[field] ? `${field}-error` : undefined} />}{errors[field] && <p className="error" id={`${field}-error`}>{errors[field]}</p>}</div>)}</div><button className="button" type="submit">Check message <Arrow /></button><p className="muted">Demo form. Your message is not sent or stored.</p><div role="status">{success && <p className="success">Your details passed validation. This is a demo; no message was sent.</p>}</div></form>;
}
