'use client';
import { useEffect, useState } from 'react';
import type { PlannerTask } from '@/lib/content';
import { parseTasks, storageKey } from '@/lib/planner';
export function Planner() {
 const [tasks, setTasks] = useState<PlannerTask[]>([]); const [ready, setReady] = useState(false); const [title, setTitle] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [filter, setFilter] = useState<'all' | 'active' | 'done'>('all');
 useEffect(() => { try { const raw = localStorage.getItem(storageKey); const parsed = parseTasks(raw); setTasks(parsed); if (raw && JSON.parse(raw).length !== parsed.length) setNotice('Some outdated saved entries could not be restored. Valid tasks were kept.'); } catch { setNotice('Saved tasks could not be read. A new list is available; browser storage may be unavailable.'); } setReady(true); }, []);
 function update(next: PlannerTask[]) { setTasks(next); try { localStorage.setItem(storageKey, JSON.stringify(next)); } catch { setNotice('Changes are available this session, but could not be saved in this browser.'); } }
 const done = tasks.filter(t => t.completed).length;
 const visible = tasks.filter(t => filter === 'all' || (filter === 'done' ? t.completed : !t.completed));
 return <div className="planner-grid"><aside className="planner-summary"><span className="meta">YOUR LIST, AT A GLANCE</span><strong>{String(tasks.length - done).padStart(2, '0')}</strong><span>tasks to move forward</span><div className="summary-row"><span>Total</span><b>{tasks.length}</b></div><div className="summary-row"><span>Completed</span><b>{done}</b></div><p className="muted">Saved on this device.<br />No account. No sync.</p></aside><section className="task-panel" aria-label="Task list"><form onSubmit={e => { e.preventDefault(); if (!title.trim()) { setError('Enter a task before adding it.'); return; } update([...tasks, { id: crypto.randomUUID(), title: title.trim(), completed: false }]); setTitle(''); setError(''); setNotice('Task added.'); }}><label htmlFor="task-title">What’s the next step?</label><div className="task-input"><input id="task-title" placeholder="e.g. Write the project introduction" value={title} maxLength={200} onChange={e => setTitle(e.target.value)} aria-invalid={!!error} aria-describedby={error ? 'task-error' : undefined} disabled={!ready} /><button className="button" disabled={!ready}>Add task +</button></div>{error && <p id="task-error" className="error" role="alert">{error}</p>}</form><div className="task-toolbar"><div className="filters" aria-label="Filter tasks">{(['all','active','done'] as const).map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f === 'done' ? 'Completed' : f === 'all' ? 'All tasks' : 'Active'}</button>)}</div><span className="meta">{visible.length} ITEMS</span></div><p className="status-message" role="status">{notice}</p>{!ready ? <p>Loading your list…</p> : !visible.length ? <div className="empty-state"><span className="meta">{tasks.length ? 'NOTHING IN THIS VIEW' : 'A CLEAN START'}</span><h2>{tasks.length ? 'No tasks here.' : 'One small step.'}</h2><p>{tasks.length ? 'Try another filter to see your list.' : 'Add your first task above. Keep it specific enough to start.'}</p></div> : <ul className="task-list">{visible.map(t => <li key={t.id}><label><input type="checkbox" checked={t.completed} onChange={() => { update(tasks.map(item => item.id === t.id ? { ...item, completed: !item.completed } : item)); setNotice(t.completed ? 'Task marked active.' : 'Task completed.'); }} /><span className={t.completed ? 'completed' : ''}>{t.title}</span></label><span className="meta task-status">{t.completed ? 'DONE' : 'TO DO'}</span><button className="delete" aria-label={`Delete ${t.title}`} onClick={() => { update(tasks.filter(item => item.id !== t.id)); setNotice('Task deleted.'); }}>Delete</button></li>)}</ul>}</section></div>;
}
